version: '3'
services:
    #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: om_app_api
    container_name: app
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
    depends_on:
      - db

  #MySQL Service
  db:
    image: mariadb:10.5.8
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: vand-db
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - .dbdata:/var/lib/mysql/
    networks:
      - app-network

#   DB access tool
  adminer:
    depends_on:
      - db
    image: adminer:4.8.0
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  .dbdata:
    driver: local
